/**
 * Shared document branding helpers.
 * Wraps any document HTML with:
 *   - Company logo at the TOP (from AppSettings)
 *   - MikeBuildsBooks logo at the BOTTOM (always, for marketing)
 */

const MIKEBUILDSBOOKS_LOGO_URL =
  "https://media.base44.com/images/public/69b9774720c1d890b1162f57/77973bc53_MikeBuildsBooksLogo.png";

/**
 * Returns an HTML block for the company header.
 */
export function buildDocHeader(company = {}) {
  const logoUrl = company.company_logo_url;
  const name = company.company_name || "";
  const address = company.company_address || "";
  const phone = company.company_phone || "";
  const email = company.company_email || "";

  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="${name}" style="max-height:48px;max-width:120px;object-fit:contain;" />`
    : name
    ? `<div style="font-size:24px;font-weight:700;color:#1e293b;">${name}</div>`
    : "";

  return `
    <div style="display:flex;align-items:center;justify-content:space-between;padding:18px 32px 14px 32px;border-bottom:2px solid #e2e8f0;margin-bottom:0;background:#ffffff;">
      <div>
        ${logoHtml}
      </div>
      <div style="text-align:right;font-size:11px;color:#64748b;line-height:1.7;">
        ${name && logoUrl ? `<div style="font-weight:600;font-size:13px;color:#1e293b;">${name}</div>` : ""}
        ${address ? `<div>${address}</div>` : ""}
        ${phone ? `<div>${phone}</div>` : ""}
        ${email ? `<div>${email}</div>` : ""}
      </div>
    </div>
  `;
}

/**
 * Returns an HTML block for the MikeBuildsBooks marketing footer.
 */
export function buildDocFooter(customFooterText = "") {
  return `
    <div style="margin-top:40px;padding:14px 32px;border-top:1px solid #e2e8f0;display:flex;align-items:center;justify-content:space-between;background:#f8fafc;">
      <div style="font-size:10px;color:#94a3b8;max-width:60%;">
        ${customFooterText || "Generated by MikeBuildsBooks &middot; Professional Construction Management"}
      </div>
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:9px;color:#94a3b8;text-transform:uppercase;letter-spacing:.05em;">Powered by</span>
        <img src="${MIKEBUILDSBOOKS_LOGO_URL}" alt="MikeBuildsBooks" style="height:38px;object-fit:contain;" />
      </div>
    </div>
  `;
}

/**
 * Wraps raw document body HTML with the full branded shell:
 * company header at top, MikeBuildsBooks footer at bottom.
 *
 * Use this when the incoming html is NOT a full HTML document
 * (i.e. it's just inner body content / a partial).
 *
 * If the html already contains <!DOCTYPE it is treated as a full document
 * and the header/footer are injected after <body> and before </body>.
 */
export function wrapDocWithBranding(html, company = {}) {
  const header = buildDocHeader(company);
  const footer = buildDocFooter(company.doc_footer_text);

  if (!html) return "";

  // If already a full document, inject inside body
  if (html.trim().toLowerCase().startsWith("<!doctype")) {
    return html
      .replace(/(<body[^>]*>)/i, `$1\n${header}`)
      .replace(/<\/body>/i, `${footer}\n</body>`);
  }

  // Otherwise wrap as full document
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <style>
    * { box-sizing: border-box; }
    body { font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0; background: #ffffff; color: #1e293b; }
    @media print {
      body { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  ${header}
  <div style="padding: 24px 32px;">
    ${html}
  </div>
  ${footer}
</body>
</html>`;
}